# Generated by Django 5.0.1 on 2024-01-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='description',
            field=models.TextField(default='Great item'),
            preserve_default=False,
        ),
    ]
